version: '3'
services:
  db:
    image: mysql/mysql-server:8.0
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASS}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_NAME}"
    volumes: 
      - ./models/dump/game_db.sql:/docker-entrypoint-initdb.d/game_db.sql
    networks:
      - mynet
    tty: true
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynet
networks:
  mynet:
    driver: "bridge"
